_BASE_: "Base-Distillation.yaml"
OUTPUT_DIR: output/distillationtmp
MODEL:
  META_ARCHITECTURE: "Distillation"
  #PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_kd"
  WEIGHTS: "projects/Distillation/pretrained/r50-r101.pth"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
    #RES2_OUT_CHANNELS: 64
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "DistillRPN"
  ROI_HEADS:
    NAME: "DistillROIHeads"

TEACHER:
  MODEL:
    RESNETS:
      DEPTH: 101

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 180000
  STEPS:
  - 120000
  - 160000

KD:
  FEATURE_ON: False
  FEATURE_LOSS_WEIGHT: 0.5
  REGION_CORRELATION_LOSS_ON: True
  REGION_CORRELATION_LOSS_WEIGHT: 1.0
  REGION_CORRELATION_LOSS_USE_BG_FEATURE: True
  REGION_CORRELATION_LOSS_WEIGHT_POOL: 1.0
  REGION_CORRELATION_POOL_LOSS: True
  FEATURE_ROIPOOL_FG_LOSS_ON: True
  FEATURE_ROIPOOL_FG_LOSS_WEIGHT: 0.5
  FEATURE_ROIPOOL_BG_LOSS_ON: True
  FEATURE_ROIPOOL_BG_LOSS_WEIGHT: 0.4
  ROI_CLS_ON: False
  ROI_CLS_LOSS_WEIGHT: 3.0
  ROI_REG_ON: False
  ROI_REG_LOSS_WEIGHT: 1.0
