_BASE_: "Base-Distillation.yaml"
OUTPUT_DIR: output/distillationtmp
MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "Distillation"
  BACKBONE:
    NAME: "build_e0_fpn_backbone_kd"

  WEIGHTS: "projects/Distillation/pretrained/eb0-r101.pth"
  EFFICIENTNET:
    NORM: "FrozenBN"
  FPN:
    IN_FEATURES: ["e2", "e3", "e4", "e5"]

  PROPOSAL_GENERATOR:
    NAME: "DistillRPN"
  ROI_HEADS:
    NAME: "DistillROIHeads"

TEACHER:
  MODEL:
    RESNETS:
      DEPTH: 101

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 180000
  STEPS:
  - 120000
  - 160000

KD:
  FEATURE_ON: True
  FEATURE_LOSS_WEIGHT: 0.5
  REGION_CORRELATION_LOSS_ON: True
  REGION_CORRELATION_LOSS_USE_BG_FEATURE: True
  REGION_CORRELATION_LOSS_WEIGHT_POOL: 2.0
  REGION_CORRELATION_POOL_LOSS: True
  FEATURE_ROIPOOL_FG_LOSS_ON: True
  FEATURE_ROIPOOL_FG_LOSS_WEIGHT: 0.5
  FEATURE_ROIPOOL_BG_LOSS_ON: True
  FEATURE_ROIPOOL_BG_LOSS_WEIGHT: 0.5
  ROI_CLS_ON: True
  ROI_CLS_LOSS_WEIGHT: 3.0
  ROI_REG_ON: True
  ROI_REG_LOSS_WEIGHT: 1.0
  USE_BG_FEATURE_MINING_THRS: True
  BG_MINING_THRS: 0.6
  BG_FEATURE_MINING_ON: True
  USE_BG_WEIGHT_SCALE: True
  BG_WEIGHT_ALPHA: 7.5

