_BASE_: "Base-Distillation.yaml"
OUTPUT_DIR: output/distillationtmp
MODEL:
  META_ARCHITECTURE: "Distillation"
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_kd"
  WEIGHTS: "projects/Distillation/pretrained/r18-r50.pth"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "DistillRPN"
  ROI_HEADS:
    NAME: "DistillROIHeads"

TEACHER:
  MODEL:
    RESNETS:
      DEPTH: 50

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 180000
  STEPS:
  - 120000
  - 160000

KD:
  FEATURE_ON: True
  FEATURE_LOSS_WEIGHT: 0.5
  REGION_CORRELATION_LOSS_ON: True
  REGION_CORRELATION_LOSS_WEIGHT: 1.0
  REGION_CORRELATION_LOSS_USE_BG_FEATURE: True
  REGION_CORRELATION_LOSS_WEIGHT_POOL: 2.0
  REGION_CORRELATION_HEAD_LOSS: False
  REGION_CORRELATION_POOL_LOSS: True
  FEATURE_ROIPOOL_FG_LOSS_ON: True
  FEATURE_ROIPOOL_FG_LOSS_WEIGHT: 0.5
  FEATURE_ROIPOOL_BG_LOSS_ON: True
  FEATURE_ROIPOOL_BG_LOSS_WEIGHT: 0.4
  #USE_POOL_PARAMETRIC_HEAD: False
  #POOL_PARAMETRIC_HEAD_NUM_CONV: 2
  ROI_CLS_ON: True
  ROI_CLS_LOSS_WEIGHT: 3.0
  ROI_REG_ON: True
  ROI_REG_LOSS_WEIGHT: 1.0
  USE_BG_FEATURE_MINING_THRS: True
  BG_MINING_THRS: 0.6
  BG_FEATURE_MINING_ON: True


